modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="l2rpgcommon"
version="${file.jarVersion}" #mandatory
displayName="L2 Archery" #mandatory
logoFile="l2rpgcommon.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2rpgcommon]]
    modId="forge"
    mandatory=true
    versionRange="[41。0。94,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2rpgcommon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2rpgcommon]]
    modId="l2library"
    mandatory=true
    versionRange="[1.5.1,)"
    ordering="AFTER"
    side="BOTH"